mydata<-read.table("~/R2/household_power_consumption.txt",header=T,sep=";",na.strings="?")
mydata$Date<-as.Date(mydata$Date, format="%d/%m/%Y")
datatrue<-subset(mydata,Date>="2007-02-01"& Date <= "2007-02-02")
rm(mydata)
datetime <- paste(as.Date(datatrue$Date), datatrue$Time)
datatrue$Datetime <- as.POSIXct(datetime)
Sys.setlocale("LC_ALL", "en_US")
plot(datatrue$Datetime,datatrue$Global_active_power,type="l", xlab="" ,ylab="Global Active Power(kilowatts)")
dev.copy(png,file="plot2.png")
dev.off()